### ISSUE TITLE
Write about future work on clustering

### ISSUE THREAD

**Issue by jiedxu** [edxu96/elec_consumption#115]
- [x] Different number of clusters (#85)
- [x] structured clustering (#81)
- [x] preprocess before similarity measures (#114)
- [x] MILP: min inter-cluster similarity and max at same time (#86)
